export * from './lib/base.entity';
export * from './lib/hostel.entity';
export * from './lib/info.entity';
export * from './lib/location.entity';
export * from './lib/prayer-room.entity';
export * from './lib/product.entity';
export * from './lib/request.entity';
export * from './lib/restaurant.entity';
export * from './lib/review.entity';